url: "https://sp301415.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Intak Hwang" # the name of your site, e.g. ACME Corp.
email: sp301415@gmail.com
author: sp301415
description: "Hello! I'm Intak Hwang (sp301415)."

sass:
  style: compressed

plugins:
  - jekyll-seo-tag

include:
  - _headers

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - bundle/
  - cache/
  - gems/
  - ruby/

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/opengraph/default.png
