url: "sp301415.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Hwang In Tak" # the name of your site, e.g. ACME Corp.

sass:
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
include:
  - _headers

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/og.png