name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    name: Build and Deploy Jekyll Site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Build Jekyll Site
        run: bundle exec jekyll build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: 57dee0c3071a38e49addeeedaebbb4ea
          command: pages deploy _site --project-name=sp301415
